version: 0.2

phases:
  install:
    commands:
      - ls -al
      - echo "Bump up go version to 1.18"
      - wget -q https://storage.googleapis.com/golang/go1.18.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go1.18.linux-amd64.tar.gz
      - export PATH="/usr/local/go/bin:$PATH" && export GOPATH="$HOME/go" && export PATH="$GOPATH/bin:$PATH"
  pre_build:
    commands:
      - echo "Setting up GitHub access"
      - go env -w GOPRIVATE=github.com/ag5/\*
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - mkdir -p /root/.ssh
      - touch /root/.ssh/id_rsa
      - echo "$CI_SSH_KEY" > /root/.ssh/id_rsa
      - chmod 700 /root/.ssh && chmod 600 /root/.ssh/id_rsa

      - echo "Download go dependencies"
      - go mod download
      - go mod vendor

      - echo "Extract git tag"
      - export GIT_TAG=${CODEBUILD_WEBHOOK_TRIGGER#*/}

      - echo "Start docker daemon"
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&

      - echo "Login into aws container registry"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Build the image and push it to the registry"
      - docker build -t $IMAGE_REPO_NAME:$GIT_TAG .
      - docker tag $IMAGE_REPO_NAME:$GIT_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$GIT_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$GIT_TAG
  post_build:
    commands:
      - echo "Send Slack notification if build step fails"
      - ./notify.sh