name: Trigger Codebuild

on:
  workflow_call:

jobs:
  Trigger-codebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: go-parq-ingester
          buildspec-override: ./buildspec.yaml
          env-vars-for-codebuild: |
            custom,
            requester,
            event-name
        env:
          custom: my environment variable
          requester: ${{ github.actor }}
          event-name: ${{ github.event_name }}
